# Generated by Django 5.2.5 on 2025-10-01 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, and underscores.', regex='^@[a-zA-Z0-9_]*$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password can only contain letters, numbers, and underscores.', regex='^@[a-zA-Z0-9_]*$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='APP/static/users')),
            ],
        ),
    ]
